<a href="https://colab.research.google.com/github/IngaBesedina/AI_ML_5/blob/main/LR_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
dataset = pd.read_csv('https://raw.githubusercontent.com/IngaBesedina/AI_ML_5/main/data/dataset.csv')
dataset.head()

     education  gender  age     income  score purchased
0     Bachelor  Female   26  2000000.0    692       yes
1  High School    Male   34    22742.0   1000       yes
2     Bachelor  Female   44        NaN    643       yes
3          PhD  Female   26    59827.0    679        no
4  High School    Male   48    35959.0    394       yes

In [27]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 5].values
print ("Матрица признаков"); print(X)
print ("Зависимая переменная"); print(y)

Матрица признаков
[['Bachelor' 'Female' 26 2000000.0 692]
 ['High School' 'Male' 34 22742.0 1000]
 ['Bachelor' 'Female' 44 nan 643]
 ['PhD' 'Female' 26 59827.0 679]
 ['High School' 'Male' 48 35959.0 394]
 ['PhD' 'Male' 46 nan 313]
 ['Bachelor' 'Female' 39 96870.0 593]
 ['Master' 'Male' 23 57715.0 331]
 ['High School' 'Female' 55 77561.0 350]
 ['PhD' 'Female' 22 93851.0 673]
 ['PhD' 'Female' 37 62608.0 808]
 ['High School' 'Male' 28 50455.0 532]
 ['Master' 'Male' 49 39211.0 721]
 ['Bachelor' 'Male' 33 25756.0 750]
 ['Bachelor' 'Male' 52 34536.0 669]
 ['Bachelor' 'Female' 27 90073.0 331]
 ['PhD' 'Male' 61 20518.0 799]
 ['High School' 'Female' 52 42733.0 414]
 ['High School' 'Female' 38 88132.0 607]
 ['High School' 'Female' 53 31184.0 686]
 ['High School' 'Male' 27 79135.0 848]
 ['PhD' 'Male' 47 nan 425]
 ['Master' 'Female' 40 48889.0 392]
 ['High School' 'Male' 27 51969.0 668]
 ['Bachelor' 'Male' 29 94626.0 714]
 ['Bachelor' 'Female' 25 87658.0 338]
 ['Master' 'Female' 32 74358.0 830]
 ['High School' 'Female' 48 83627.0 329]
 ['Bachelor' 'Female' 55 65723.0 791]
 ['Master' 'Male' 19 95182.0 830]
 ['High School' 'Male' 57 45456.0 820]
 ['Master' 'Female' 36 48210.0 397]
 ['Bachelor' 'Male' 58 53831.0 784]
 ['Bachelor' 'Male' 27 24930.0 544]
 ['Bachelor' 'Male' 49 47174.0 421]
 ['Master' 'Female' 26 96087.0 785]
 ['PhD' 'Female' 46 89598.0 464]
 ['PhD' 'Male' 38 24216.0 834]
 ['High School' 'Female' 25 21670.0 570]
 ['Master' 'Male' 36 95712.0 689]
 ['High School' 'Female' 40 79589.0 456]
 ['Bachelor' 'Male' 61 59683.0 676]
 ['Master' 'Male' 39 24054.0 711]
 ['Master' 'Female' 48 52285.0 663]
 ['PhD' 'Male' 52 32298.0 613]
 ['Bachelor' 'Female' 43 45519.0 385]
 ['PhD' 'Female' 61 nan 747]
 ['High School' 'Female' 61 90569.0 629]
 ['Bachelor' 'Male' 32 98207.0 736]
 ['Bachelor' 'Male' 38 86743.0 388]
 ['Master' 'Female' 61 34506.0 669]
 ['PhD' 'Female' 31 89328.0 768]
 ['PhD' 'Male' 50 43816.0 524]
 ['High School' 'Female' 33 57956.0 720]
 ['Master' 'Female' 51 75591.0 412]
 ['PhD' 'Male' 42 23298.0 753]
 ['PhD' 'Male' 39 28653.0 562]
 ['Bachelor' 'Male' 19 86466.0 576]
 ['Master' 'Female' 25 24582.0 426]
 ['High School' 'Female' 36 81805.0 360]
 ['High School' 'Male' 30 75701.0 444]
 ['PhD' 'Male' 25 44565.0 557]
 ['PhD' 'Female' 53 68398.0 555]
 ['Bachelor' 'Female' 32 98184.0 476]
 ['Bachelor' 'Male' 60 99388.0 494]
 ['Master' 'Female' 26 58850.0 775]
 ['High School' 'Male' 37 88279.0 649]
 ['Master' 'Female' 29 60999.0 323]
 ['Bachelor' 'Male' 54 89711.0 480]
 ['PhD' 'Female' 58 26205.0 719]
 ['Master' 'Male' 59 53168.0 585]
 ['Master' 'Female' 40 22750.0 631]
 ['Master' 'Male' 61 65847.0 398]
 ['High School' 'Female' 54 63151.0 595]
 ['High School' 'Female' 64 71221.0 587]
 ['Bachelor' 'Male' 46 95229.0 360]
 ['Bachelor' 'Female' 28 97585.0 838]
 ['PhD' 'Male' 59 25233.0 538]
 ['High School' 'Male' 36 92515.0 428]
 ['High School' 'Female' 52 47105.0 758]
 ['Master' 'Female' 58 93823.0 480]
 ['High School' 'Female' 20 61146.0 696]
 ['Master' 'Male' 33 28480.0 454]
 ['PhD' 'Male' 20 nan 823]
 ['Master' 'Female' 45 93468.0 442]
 ['PhD' 'Female' 28 53183.0 447]
 ['High School' 'Female' 60 63906.0 510]
 ['Bachelor' 'Male' 49 22693.0 306]
 ['PhD' 'Female' 35 58921.0 468]
 ['Bachelor' 'Female' 57 36806.0 614]
 ['Master' 'Female' 22 47265.0 526]
 ['Bachelor' 'Male' 47 43757.0 518]
 ['PhD' 'Male' 43 25321.0 824]
 ['High School' 'Female' 42 90260.0 843]
 ['High School' 'Male' 56 56788.0 752]
 ['High School' 'Female' 34 46972.0 694]
 ['PhD' 'Female' 59 97596.0 348]
 ['High School' 'Male' 23 91811.0 477]
 ['PhD' 'Female' 26 62761.0 595]
 ['Bachelor' 'Male' 58 85715.0 612]]
Зависимая переменная
['yes' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no'
 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'no'
 'no' 'no' 'no' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'no'
 'yes' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'no'
 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'no' 'no' 'no' 'yes' 'no' 'no'
 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'no' 'no' 'yes' 'no' 'yes' 'yes'
 'no' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'no' 'no' 'yes' 'no' 'yes'
 'yes' 'no' 'no' 'yes' 'no' 'no' 'no' 'yes']

In [29]:
# Новая версия класса-трансформера, предыдущая Imputer - устарела
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, 3:])
X_without_nan = X.copy()
X_without_nan[:, 3:] = imputer.transform(X[:, 3:])
X_without_nan

array([['Bachelor', 'Female', 26, 2000000.0, 692.0],
       ['High School', 'Male', 34, 22742.0, 1000.0],
       ['Bachelor', 'Female', 44, 81868.27368421052, 643.0],
       ['PhD', 'Female', 26, 59827.0, 679.0],
       ['High School', 'Male', 48, 35959.0, 394.0],
       ['PhD', 'Male', 46, 81868.27368421052, 313.0],
       ['Bachelor', 'Female', 39, 96870.0, 593.0],
       ['Master', 'Male', 23, 57715.0, 331.0],
       ['High School', 'Female', 55, 77561.0, 350.0],
       ['PhD', 'Female', 22, 93851.0, 673.0],
       ['PhD', 'Female', 37, 62608.0, 808.0],
       ['High School', 'Male', 28, 50455.0, 532.0],
       ['Master', 'Male', 49, 39211.0, 721.0],
       ['Bachelor', 'Male', 33, 25756.0, 750.0],
       ['Bachelor', 'Male', 52, 34536.0, 669.0],
       ['Bachelor', 'Female', 27, 90073.0, 331.0],
       ['PhD', 'Male', 61, 20518.0, 799.0],
       ['High School', 'Female', 52, 42733.0, 414.0],
       ['High School', 'Female', 38, 88132.0, 607.0],
       ['High School', 'Female', 53, 31184.0, 686.0],
       ['High School', 'Male', 27, 79135.0, 848.0],
       ['PhD', 'Male', 47, 81868.27368421052, 425.0],
       ['Master', 'Female', 40, 48889.0, 392.0],
       ['High School', 'Male', 27, 51969.0, 668.0],
       ['Bachelor', 'Male', 29, 94626.0, 714.0],
       ['Bachelor', 'Female', 25, 87658.0, 338.0],
       ['Master', 'Female', 32, 74358.0, 830.0],
       ['High School', 'Female', 48, 83627.0, 329.0],
       ['Bachelor', 'Female', 55, 65723.0, 791.0],
       ['Master', 'Male', 19, 95182.0, 830.0],
       ['High School', 'Male', 57, 45456.0, 820.0],
       ['Master', 'Female', 36, 48210.0, 397.0],
       ['Bachelor', 'Male', 58, 53831.0, 784.0],
       ['Bachelor', 'Male', 27, 24930.0, 544.0],
       ['Bachelor', 'Male', 49, 47174.0, 421.0],
       ['Master', 'Female', 26, 96087.0, 785.0],
       ['PhD', 'Female', 46, 89598.0, 464.0],
       ['PhD', 'Male', 38, 24216.0, 834.0],
       ['High School', 'Female', 25, 21670.0, 570.0],
       ['Master', 'Male', 36, 95712.0, 689.0],
       ['High School', 'Female', 40, 79589.0, 456.0],
       ['Bachelor', 'Male', 61, 59683.0, 676.0],
       ['Master', 'Male', 39, 24054.0, 711.0],
       ['Master', 'Female', 48, 52285.0, 663.0],
       ['PhD', 'Male', 52, 32298.0, 613.0],
       ['Bachelor', 'Female', 43, 45519.0, 385.0],
       ['PhD', 'Female', 61, 81868.27368421052, 747.0],
       ['High School', 'Female', 61, 90569.0, 629.0],
       ['Bachelor', 'Male', 32, 98207.0, 736.0],
       ['Bachelor', 'Male', 38, 86743.0, 388.0],
       ['Master', 'Female', 61, 34506.0, 669.0],
       ['PhD', 'Female', 31, 89328.0, 768.0],
       ['PhD', 'Male', 50, 43816.0, 524.0],
       ['High School', 'Female', 33, 57956.0, 720.0],
       ['Master', 'Female', 51, 75591.0, 412.0],
       ['PhD', 'Male', 42, 23298.0, 753.0],
       ['PhD', 'Male', 39, 28653.0, 562.0],
       ['Bachelor', 'Male', 19, 86466.0, 576.0],
       ['Master', 'Female', 25, 24582.0, 426.0],
       ['High School', 'Female', 36, 81805.0, 360.0],
       ['High School', 'Male', 30, 75701.0, 444.0],
       ['PhD', 'Male', 25, 44565.0, 557.0],
       ['PhD', 'Female', 53, 68398.0, 555.0],
       ['Bachelor', 'Female', 32, 98184.0, 476.0],
       ['Bachelor', 'Male', 60, 99388.0, 494.0],
       ['Master', 'Female', 26, 58850.0, 775.0],
       ['High School', 'Male', 37, 88279.0, 649.0],
       ['Master', 'Female', 29, 60999.0, 323.0],
       ['Bachelor', 'Male', 54, 89711.0, 480.0],
       ['PhD', 'Female', 58, 26205.0, 719.0],
       ['Master', 'Male', 59, 53168.0, 585.0],
       ['Master', 'Female', 40, 22750.0, 631.0],
       ['Master', 'Male', 61, 65847.0, 398.0],
       ['High School', 'Female', 54, 63151.0, 595.0],
       ['High School', 'Female', 64, 71221.0, 587.0],
       ['Bachelor', 'Male', 46, 95229.0, 360.0],
       ['Bachelor', 'Female', 28, 97585.0, 838.0],
       ['PhD', 'Male', 59, 25233.0, 538.0],
       ['High School', 'Male', 36, 92515.0, 428.0],
       ['High School', 'Female', 52, 47105.0, 758.0],
       ['Master', 'Female', 58, 93823.0, 480.0],
       ['High School', 'Female', 20, 61146.0, 696.0],
       ['Master', 'Male', 33, 28480.0, 454.0],
       ['PhD', 'Male', 20, 81868.27368421052, 823.0],
       ['Master', 'Female', 45, 93468.0, 442.0],
       ['PhD', 'Female', 28, 53183.0, 447.0],
       ['High School', 'Female', 60, 63906.0, 510.0],
       ['Bachelor', 'Male', 49, 22693.0, 306.0],
       ['PhD', 'Female', 35, 58921.0, 468.0],
       ['Bachelor', 'Female', 57, 36806.0, 614.0],
       ['Master', 'Female', 22, 47265.0, 526.0],
       ['Bachelor', 'Male', 47, 43757.0, 518.0],
       ['PhD', 'Male', 43, 25321.0, 824.0],
       ['High School', 'Female', 42, 90260.0, 843.0],
       ['High School', 'Male', 56, 56788.0, 752.0],
       ['High School', 'Female', 34, 46972.0, 694.0],
       ['PhD', 'Female', 59, 97596.0, 348.0],
       ['High School', 'Male', 23, 91811.0, 477.0],
       ['PhD', 'Female', 26, 62761.0, 595.0],
       ['Bachelor', 'Male', 58, 85715.0, 612.0]], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
print("Зависимая переменная до обработки")
print(y)
y = labelencoder_y.fit_transform(y)
print("Зависимая переменная после обработки")
print(y)

Зависимая переменная до обработки
['yes' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no'
 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'no'
 'no' 'no' 'no' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'no'
 'yes' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'no'
 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'no' 'no' 'no' 'yes' 'no' 'no'
 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'no' 'no' 'yes' 'no' 'yes' 'yes'
 'no' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'no' 'no' 'yes' 'no' 'yes'
 'yes' 'no' 'no' 'yes' 'no' 'no' 'no' 'yes']
Зависимая переменная после обработки
[1 1 1 0 1 0 0 1 1 0 1 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0
 0 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1]

In [31]:
# создаем копию "грязного" объекта: спропусками и некодированными категориями
X_dirty = X.copy()
X_dirty

array([['Bachelor', 'Female', 26, 2000000.0, 692],
       ['High School', 'Male', 34, 22742.0, 1000],
       ['Bachelor', 'Female', 44, nan, 643],
       ['PhD', 'Female', 26, 59827.0, 679],
       ['High School', 'Male', 48, 35959.0, 394],
       ['PhD', 'Male', 46, nan, 313],
       ['Bachelor', 'Female', 39, 96870.0, 593],
       ['Master', 'Male', 23, 57715.0, 331],
       ['High School', 'Female', 55, 77561.0, 350],
       ['PhD', 'Female', 22, 93851.0, 673],
       ['PhD', 'Female', 37, 62608.0, 808],
       ['High School', 'Male', 28, 50455.0, 532],
       ['Master', 'Male', 49, 39211.0, 721],
       ['Bachelor', 'Male', 33, 25756.0, 750],
       ['Bachelor', 'Male', 52, 34536.0, 669],
       ['Bachelor', 'Female', 27, 90073.0, 331],
       ['PhD', 'Male', 61, 20518.0, 799],
       ['High School', 'Female', 52, 42733.0, 414],
       ['High School', 'Female', 38, 88132.0, 607],
       ['High School', 'Female', 53, 31184.0, 686],
       ['High School', 'Male', 27, 79135.0, 848],
       ['PhD', 'Male', 47, nan, 425],
       ['Master', 'Female', 40, 48889.0, 392],
       ['High School', 'Male', 27, 51969.0, 668],
       ['Bachelor', 'Male', 29, 94626.0, 714],
       ['Bachelor', 'Female', 25, 87658.0, 338],
       ['Master', 'Female', 32, 74358.0, 830],
       ['High School', 'Female', 48, 83627.0, 329],
       ['Bachelor', 'Female', 55, 65723.0, 791],
       ['Master', 'Male', 19, 95182.0, 830],
       ['High School', 'Male', 57, 45456.0, 820],
       ['Master', 'Female', 36, 48210.0, 397],
       ['Bachelor', 'Male', 58, 53831.0, 784],
       ['Bachelor', 'Male', 27, 24930.0, 544],
       ['Bachelor', 'Male', 49, 47174.0, 421],
       ['Master', 'Female', 26, 96087.0, 785],
       ['PhD', 'Female', 46, 89598.0, 464],
       ['PhD', 'Male', 38, 24216.0, 834],
       ['High School', 'Female', 25, 21670.0, 570],
       ['Master', 'Male', 36, 95712.0, 689],
       ['High School', 'Female', 40, 79589.0, 456],
       ['Bachelor', 'Male', 61, 59683.0, 676],
       ['Master', 'Male', 39, 24054.0, 711],
       ['Master', 'Female', 48, 52285.0, 663],
       ['PhD', 'Male', 52, 32298.0, 613],
       ['Bachelor', 'Female', 43, 45519.0, 385],
       ['PhD', 'Female', 61, nan, 747],
       ['High School', 'Female', 61, 90569.0, 629],
       ['Bachelor', 'Male', 32, 98207.0, 736],
       ['Bachelor', 'Male', 38, 86743.0, 388],
       ['Master', 'Female', 61, 34506.0, 669],
       ['PhD', 'Female', 31, 89328.0, 768],
       ['PhD', 'Male', 50, 43816.0, 524],
       ['High School', 'Female', 33, 57956.0, 720],
       ['Master', 'Female', 51, 75591.0, 412],
       ['PhD', 'Male', 42, 23298.0, 753],
       ['PhD', 'Male', 39, 28653.0, 562],
       ['Bachelor', 'Male', 19, 86466.0, 576],
       ['Master', 'Female', 25, 24582.0, 426],
       ['High School', 'Female', 36, 81805.0, 360],
       ['High School', 'Male', 30, 75701.0, 444],
       ['PhD', 'Male', 25, 44565.0, 557],
       ['PhD', 'Female', 53, 68398.0, 555],
       ['Bachelor', 'Female', 32, 98184.0, 476],
       ['Bachelor', 'Male', 60, 99388.0, 494],
       ['Master', 'Female', 26, 58850.0, 775],
       ['High School', 'Male', 37, 88279.0, 649],
       ['Master', 'Female', 29, 60999.0, 323],
       ['Bachelor', 'Male', 54, 89711.0, 480],
       ['PhD', 'Female', 58, 26205.0, 719],
       ['Master', 'Male', 59, 53168.0, 585],
       ['Master', 'Female', 40, 22750.0, 631],
       ['Master', 'Male', 61, 65847.0, 398],
       ['High School', 'Female', 54, 63151.0, 595],
       ['High School', 'Female', 64, 71221.0, 587],
       ['Bachelor', 'Male', 46, 95229.0, 360],
       ['Bachelor', 'Female', 28, 97585.0, 838],
       ['PhD', 'Male', 59, 25233.0, 538],
       ['High School', 'Male', 36, 92515.0, 428],
       ['High School', 'Female', 52, 47105.0, 758],
       ['Master', 'Female', 58, 93823.0, 480],
       ['High School', 'Female', 20, 61146.0, 696],
       ['Master', 'Male', 33, 28480.0, 454],
       ['PhD', 'Male', 20, nan, 823],
       ['Master', 'Female', 45, 93468.0, 442],
       ['PhD', 'Female', 28, 53183.0, 447],
       ['High School', 'Female', 60, 63906.0, 510],
       ['Bachelor', 'Male', 49, 22693.0, 306],
       ['PhD', 'Female', 35, 58921.0, 468],
       ['Bachelor', 'Female', 57, 36806.0, 614],
       ['Master', 'Female', 22, 47265.0, 526],
       ['Bachelor', 'Male', 47, 43757.0, 518],
       ['PhD', 'Male', 43, 25321.0, 824],
       ['High School', 'Female', 42, 90260.0, 843],
       ['High School', 'Male', 56, 56788.0, 752],
       ['High School', 'Female', 34, 46972.0, 694],
       ['PhD', 'Female', 59, 97596.0, 348],
       ['High School', 'Male', 23, 91811.0, 477],
       ['PhD', 'Female', 26, 62761.0, 595],
       ['Bachelor', 'Male', 58, 85715.0, 612]], dtype=object)

In [33]:
# Современный метод трансформации признаков
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# создаем список трансформеров
transformers = [
    ('onehot', OneHotEncoder(), [0,1]),
    ('imp', SimpleImputer(), [2, 3, 4])
]

# Создаем объект ColumnTransformer и передаем ему список трансформеров
ct = ColumnTransformer(transformers)

# Выполняем трансформацию признаков
X_transformed = ct.fit_transform(X_dirty)
print(X_transformed.shape)
X_transformed

(100, 9)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.60000000e+01, 2.00000000e+06,
        6.92000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.40000000e+01, 2.27420000e+04,
        1.00000000e+03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.40000000e+01, 8.18682737e+04,
        6.43000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.60000000e+01, 5.98270000e+04,
        6.79000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.80000000e+01, 3.59590000e+04,
        3.94000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.60000000e+01, 8.18682737e+04,
        3.13000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.90000000e+01, 9.68700000e+04,
        5.93000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.30000000e+01, 5.77150000e+04,
        3.31000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.50000000e+01, 7.75610000e+04,
        3.50000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.20000000e+01, 9.38510000e+04,
        6.73000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.26080000e+04,
        8.08000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.80000000e+01, 5.04550000e+04,
        5.32000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.90000000e+01, 3.92110000e+04,
        7.21000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.30000000e+01, 2.57560000e+04,
        7.50000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.20000000e+01, 3.45360000e+04,
        6.69000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.70000000e+01, 9.00730000e+04,
        3.31000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 6.10000000e+01, 2.05180000e+04,
        7.99000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.20000000e+01, 4.27330000e+04,
        4.14000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.80000000e+01, 8.81320000e+04,
        6.07000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.30000000e+01, 3.11840000e+04,
        6.86000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 7.91350000e+04,
        8.48000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.70000000e+01, 8.18682737e+04,
        4.25000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 4.88890000e+04,
        3.92000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 5.19690000e+04,
        6.68000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.90000000e+01, 9.46260000e+04,
        7.14000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.50000000e+01, 8.76580000e+04,
        3.38000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.20000000e+01, 7.43580000e+04,
        8.30000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.80000000e+01, 8.36270000e+04,
        3.29000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.50000000e+01, 6.57230000e+04,
        7.91000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 1.90000000e+01, 9.51820000e+04,
        8.30000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.70000000e+01, 4.54560000e+04,
        8.20000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.60000000e+01, 4.82100000e+04,
        3.97000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.80000000e+01, 5.38310000e+04,
        7.84000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 2.49300000e+04,
        5.44000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.90000000e+01, 4.71740000e+04,
        4.21000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.60000000e+01, 9.60870000e+04,
        7.85000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.60000000e+01, 8.95980000e+04,
        4.64000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 2.42160000e+04,
        8.34000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.50000000e+01, 2.16700000e+04,
        5.70000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.60000000e+01, 9.57120000e+04,
        6.89000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 7.95890000e+04,
        4.56000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 6.10000000e+01, 5.96830000e+04,
        6.76000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.90000000e+01, 2.40540000e+04,
        7.11000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.80000000e+01, 5.22850000e+04,
        6.63000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.20000000e+01, 3.22980000e+04,
        6.13000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.30000000e+01, 4.55190000e+04,
        3.85000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 6.10000000e+01, 8.18682737e+04,
        7.47000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 6.10000000e+01, 9.05690000e+04,
        6.29000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.20000000e+01, 9.82070000e+04,
        7.36000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 8.67430000e+04,
        3.88000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 6.10000000e+01, 3.45060000e+04,
        6.69000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.10000000e+01, 8.93280000e+04,
        7.68000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.00000000e+01, 4.38160000e+04,
        5.24000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.30000000e+01, 5.79560000e+04,
        7.20000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.10000000e+01, 7.55910000e+04,
        4.12000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.20000000e+01, 2.32980000e+04,
        7.53000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.90000000e+01, 2.86530000e+04,
        5.62000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 1.90000000e+01, 8.64660000e+04,
        5.76000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.50000000e+01, 2.45820000e+04,
        4.26000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.60000000e+01, 8.18050000e+04,
        3.60000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.00000000e+01, 7.57010000e+04,
        4.44000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.50000000e+01, 4.45650000e+04,
        5.57000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.30000000e+01, 6.83980000e+04,
        5.55000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.20000000e+01, 9.81840000e+04,
        4.76000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 6.00000000e+01, 9.93880000e+04,
        4.94000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.60000000e+01, 5.88500000e+04,
        7.75000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.70000000e+01, 8.82790000e+04,
        6.49000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.90000000e+01, 6.09990000e+04,
        3.23000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.40000000e+01, 8.97110000e+04,
        4.80000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.80000000e+01, 2.62050000e+04,
        7.19000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.90000000e+01, 5.31680000e+04,
        5.85000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 2.27500000e+04,
        6.31000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 6.10000000e+01, 6.58470000e+04,
        3.98000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.40000000e+01, 6.31510000e+04,
        5.95000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 6.40000000e+01, 7.12210000e+04,
        5.87000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.60000000e+01, 9.52290000e+04,
        3.60000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.80000000e+01, 9.75850000e+04,
        8.38000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.90000000e+01, 2.52330000e+04,
        5.38000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.60000000e+01, 9.25150000e+04,
        4.28000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.20000000e+01, 4.71050000e+04,
        7.58000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.80000000e+01, 9.38230000e+04,
        4.80000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.00000000e+01, 6.11460000e+04,
        6.96000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 3.30000000e+01, 2.84800000e+04,
        4.54000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.00000000e+01, 8.18682737e+04,
        8.23000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.50000000e+01, 9.34680000e+04,
        4.42000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.80000000e+01, 5.31830000e+04,
        4.47000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 6.00000000e+01, 6.39060000e+04,
        5.10000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.90000000e+01, 2.26930000e+04,
        3.06000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.89210000e+04,
        4.68000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.70000000e+01, 3.68060000e+04,
        6.14000000e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.20000000e+01, 4.72650000e+04,
        5.26000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.70000000e+01, 4.37570000e+04,
        5.18000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 4.30000000e+01, 2.53210000e+04,
        8.24000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 4.20000000e+01, 9.02600000e+04,
        8.43000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.60000000e+01, 5.67880000e+04,
        7.52000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.40000000e+01, 4.69720000e+04,
        6.94000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 5.90000000e+01, 9.75960000e+04,
        3.48000000e+02],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 2.30000000e+01, 9.18110000e+04,
        4.77000000e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.60000000e+01, 6.27610000e+04,
        5.95000000e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 5.80000000e+01, 8.57150000e+04,
        6.12000000e+02]])

In [36]:
# Можно преобразовать полученный многомерный массив обратно в Dataframe
X_data = pd.DataFrame(
    X_transformed,
    columns=['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'Age', 'Income', 'Score'])
X_data

     C1   C2   C3   C4   C5   C6   Age        Income   Score
0   1.0  0.0  0.0  0.0  1.0  0.0  26.0  2.000000e+06   692.0
1   0.0  1.0  0.0  0.0  0.0  1.0  34.0  2.274200e+04  1000.0
2   1.0  0.0  0.0  0.0  1.0  0.0  44.0  8.186827e+04   643.0
3   0.0  0.0  0.0  1.0  1.0  0.0  26.0  5.982700e+04   679.0
4   0.0  1.0  0.0  0.0  0.0  1.0  48.0  3.595900e+04   394.0
..  ...  ...  ...  ...  ...  ...   ...           ...     ...
95  0.0  1.0  0.0  0.0  1.0  0.0  34.0  4.697200e+04   694.0
96  0.0  0.0  0.0  1.0  1.0  0.0  59.0  9.759600e+04   348.0
97  0.0  1.0  0.0  0.0  0.0  1.0  23.0  9.181100e+04   477.0
98  0.0  0.0  0.0  1.0  1.0  0.0  26.0  6.276100e+04   595.0
99  1.0  0.0  0.0  0.0  0.0  1.0  58.0  8.571500e+04   612.0

[100 rows x 9 columns]